#!/bin/bash 

cd ~
git clone https://github.com/yorokobi/vim-splunk.git
if [ ! -d ~/.vim/ftdetect ] ; then mkdir -p ~/.vim/ftdetect ; fi
if [ ! -d ~/.vim/syntax ] ; then mkdir -p ~/.vim/syntax ; fi
ln -s ~/git-projects/vim-splunk/ftdetect/splunk.vim ~/.vim/ftdetect/splunk.vim
ln -s ~/git-projects/vim-splunk/syntax/* ~/.vim/syntax/
echo "Run this command: alias vim=vim"
echo "alias vi=vim" >> ~/bash_profile

